on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches: [ "master" ]

jobs:
  pull_package:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull package
        run: |
          docker pull ghcr.io/xiaohuan2023/docker-demo
